### ISSUE TITLE
Make `get-metadata` machine-readable?

### ISSUE THREAD

**Issue by nickp60** [papaemmelab/isabl_cli#38]
Hi all!  Are there any consequences to removing the `.expandtabs()` here?  It would be great for this to output a regular tab-delimited file; as is, parsing is difficult due to the variable number of spaces.
https://github.com/papaemmelab/isabl_cli/blob/efe7bc9cddd894ed4fd207705d4036a3d3d93016/isabl_cli/commands.py#L196

**Comment by juanesarango** [comment]
The `json` output is the machine-readable one. The default one is with expanded tabs is prettified for been more human-readable.

In what cases you will need it as a regular tsv?

**Comment by juanesarango** [comment]
what about creating a `--tsv` option, similar to `--json`. For standard tsv, while keeping the prettified as default?

**Comment by nickp60** [comment]
Thanks for your reply! A `--tsv` option would be good; though as a cli tool having a `--pretty` output might be more unix-friendly option, with standard delimited output as the default. Having machine-readable output is needed for any sort of piping operations.

**Comment by juanesarango** [comment]
Let's hear some opinions, @funnell @ddomenico what do you think? Having `--tsv` as option with prettified by default, or `--pretty` as option with tsv as default. 

@nickp60 open to make a quick PR with what people decide? Thanks!

**Comment by nickp60** [comment]
Thanks for the consideration!  I have added a PR for the --pretty version, but I'm happy to change it if people vote the other way :)

**Comment by funnell** [comment]
if I think about the process of how I use `get-metadata` I probably run it a few times, modify my filters, and inspect the output before piping or redirecting, so I don't mind having prettified by default.

another suggestion I'll throw out there is to have a `--format` option with the default set to "auto", and then it could be set to json, tsv, or csv.
otherwise the --json and --tsv/--pretty flags will conflict
