### ISSUE TITLE
Running Project Merge Analyses breaks after version bump

### ISSUE THREAD

**Issue by nickp60** [papaemmelab/isabl_cli#45]
* isabl_cli version: bbc76fbb9
* Python version: Python 3.11.0
* Operating System: linux

### Description

I want to merge the results from application ID 22, (preprocesssing v2.0.3) on a set of samples.  I successfully ran
```
$ isabl merge-project-analyses --project 6 --application 22
Retrieving 808 from analyses API endpoint...  
```

Then, we made some changes to the app, and incremented the patch version (preprocessing v2.0.4).  Running the same command fails with the following:

```
$ isabl merge-project-analyses --project 6 --application 22
Retrieving 0 from analyses API endpoint...          
Not enough analyses for Project(6) merge, at least 2 required but got: 0
```

### What I Did

I temporarily changed the version variable back to match the requested application (`VERSION = "2.0.3"`) and reran the command, which executed successfully.  It appears that merges can only be performed when the live app version matches the requested application.

**Comment by juanesarango** [comment]
Hi @nickp60 sorry I just saw this. Hope you figured the problem already. This is expected behavior.

When bumping to a new version, isabl will create a new Application record. So if `Preprocesssing v2.0.3` had `pk=22`, then `Preprocesssing v2.0.4` will have a new `pk`. 

This default behavior allows to keep provenance and reproducibility of the results as we keep introducing new versions. But I'm aware sometimes this can be cumbersome and not desired, so what I do is that I modified in the database, from the admin, the version of the Application `pk=22`. This way, when you change the version in your app it won't create a new record.

**Comment by nickp60** [comment]
Thanks.  Its a bit of  bummer to not be able to aggregate after things like patching a app but we can work around it.

**Comment by juanesarango** [comment]
yes, that's true. In those cases, we don't create a new app in the db, by changing the version field of the current app record.

Your specific case would be to aggregate different app records, basically same app with older versions. I think if you have different versions you shouldn't combine results together, as different versions are usually not comparable.

If you have any idea of how this behavior could be achieved, Im open to suggestions. I find it hard specially as the merge method is defined only in one of the apps.

**Comment by nickp60** [comment]
Yes, totally agree.  this touches on a bigger issue of how to version apps, but I think there is another open issue or PR about that already.  thanks again!

**Comment by funnell** [comment]
it would be nice to not need to change version fields in the app records directly 😄

**Comment by nickp60** [comment]
linking https://github.com/papaemmelab/isabl_cli/issues/32
